global:
  scrape_interval: 15s

scrape_configs:
  - job_name: node
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: apache-exporter
    static_configs:
      - targets: ["apache-exporter:9117"]
